services:
  db:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - django_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local;'"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network

  classifier:
    build: ./classifier
    command: python classify.py
    volumes:
      - ./classifier:/code
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  cassandra_data:
